[package]
name = "libstrophe-static-sys"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
num_cpus = "1.16.0"

